BEGIN;

CREATE TABLE staff_advances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    division_id BIGINT NOT NULL REFERENCES divisions(id) ON DELETE RESTRICT,
    finance_account_id BIGINT NOT NULL REFERENCES finance_accounts(id) ON DELETE RESTRICT,
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    recovery_mode TEXT NOT NULL CHECK (recovery_mode IN ('salary_deduction', 'direct_repayment')),
    installment_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (installment_amount >= 0),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'settled', 'void')),
    issued_at TIMESTAMPTZ NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    finance_transaction_id BIGINT REFERENCES finance_transactions(id) ON DELETE SET NULL,
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    voided_at TIMESTAMPTZ,
    voided_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    void_reason TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_staff_advances_user_status ON staff_advances(user_id, status);

CREATE TABLE staff_advance_repayments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_advance_id BIGINT NOT NULL REFERENCES staff_advances(id) ON DELETE RESTRICT,
    payroll_payment_id BIGINT REFERENCES payroll_payments(id) ON DELETE RESTRICT,
    finance_transaction_id BIGINT REFERENCES finance_transactions(id) ON DELETE SET NULL,
    amount NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    repayment_method TEXT NOT NULL,
    repaid_at TIMESTAMPTZ NOT NULL,
    voided_at TIMESTAMPTZ,
    voided_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    void_reason TEXT NOT NULL DEFAULT '',
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX idx_staff_advance_repayment_payroll
    ON staff_advance_repayments(staff_advance_id, payroll_payment_id)
    WHERE payroll_payment_id IS NOT NULL;

COMMIT;
