-- Backfill granular PostgreSQL role permissions for existing installations.
-- This migration is additive and does not modify previous migrations.

-- Same-module CRUD bundles for permissions that now support explicit CRUD keys.
INSERT INTO role_permissions (role_id, permission)
SELECT rp.role_id, expanded.permission
FROM role_permissions rp
JOIN (
    VALUES
        ('users.manage', 'users.view'),
        ('users.manage', 'users.create'),
        ('users.manage', 'users.update'),
        ('users.manage', 'users.delete'),
        ('roles.manage', 'roles.view'),
        ('roles.manage', 'roles.create'),
        ('roles.manage', 'roles.update'),
        ('roles.manage', 'roles.delete'),
        ('user_divisions.manage', 'user_divisions.view'),
        ('user_divisions.manage', 'user_divisions.create'),
        ('user_divisions.manage', 'user_divisions.update'),
        ('user_divisions.manage', 'user_divisions.delete'),
        ('divisions.manage', 'divisions.view'),
        ('divisions.manage', 'divisions.create'),
        ('divisions.manage', 'divisions.update'),
        ('divisions.manage', 'divisions.delete'),
        ('admissions.manage', 'admissions.view'),
        ('admissions.manage', 'admissions.create'),
        ('admissions.manage', 'admissions.update'),
        ('admissions.manage', 'admissions.delete'),
        ('coaches.manage', 'coaches.view'),
        ('coaches.manage', 'coaches.create'),
        ('coaches.manage', 'coaches.update'),
        ('coaches.manage', 'coaches.delete'),
        ('payroll.manage', 'payroll.view'),
        ('payroll.manage', 'payroll.create'),
        ('payroll.manage', 'payroll.update'),
        ('payroll.manage', 'payroll.delete'),
        ('training_programs.manage', 'training_programs.view'),
        ('training_programs.manage', 'training_programs.create'),
        ('training_programs.manage', 'training_programs.update'),
        ('training_programs.manage', 'training_programs.delete'),
        ('student_groups.manage', 'student_groups.view'),
        ('student_groups.manage', 'student_groups.create'),
        ('student_groups.manage', 'student_groups.update'),
        ('student_groups.manage', 'student_groups.delete'),
        ('attendance.manage', 'attendance.view'),
        ('attendance.manage', 'attendance.update'),
        ('courts.manage', 'courts.view'),
        ('courts.manage', 'courts.create'),
        ('courts.manage', 'courts.update'),
        ('courts.manage', 'courts.delete'),
        ('space_bookings.manage', 'space_bookings.view'),
        ('space_bookings.manage', 'space_bookings.create'),
        ('space_bookings.manage', 'space_bookings.update'),
        ('space_bookings.manage', 'space_bookings.delete'),
        ('booking_requests.manage', 'booking_requests.view'),
        ('booking_requests.manage', 'booking_requests.update'),
        ('one_to_one.manage', 'one_to_one.view'),
        ('one_to_one.manage', 'one_to_one.create'),
        ('one_to_one.manage', 'one_to_one.update'),
        ('one_to_one.manage', 'one_to_one.delete'),
        ('one_to_one_bookings.manage', 'one_to_one_bookings.view'),
        ('one_to_one_bookings.manage', 'one_to_one_bookings.create'),
        ('one_to_one_bookings.manage', 'one_to_one_bookings.update'),
        ('one_to_one_bookings.manage', 'one_to_one_bookings.delete'),
        ('mcp.manage', 'mcp.view'),
        ('mcp.manage', 'mcp.create'),
        ('mcp.manage', 'mcp.update'),
        ('mcp.manage', 'mcp.delete'),
        ('mcp_pricing.manage', 'mcp_pricing.view'),
        ('mcp_pricing.manage', 'mcp_pricing.create'),
        ('mcp_pricing.manage', 'mcp_pricing.update'),
        ('mcp_pricing.manage', 'mcp_pricing.delete'),
        ('mcp_receivables.manage', 'mcp_receivables.view'),
        ('mcp_receivables.manage', 'mcp_receivables.create'),
        ('mcp_receivables.manage', 'mcp_receivables.update'),
        ('mcp_receivables.manage', 'mcp_receivables.delete'),
        ('pricing.manage', 'pricing.view'),
        ('pricing.manage', 'pricing.create'),
        ('pricing.manage', 'pricing.update'),
        ('pricing.manage', 'pricing.delete'),
        ('finance.manage', 'finance.view'),
        ('finance.manage', 'finance.create'),
        ('finance.manage', 'finance.update'),
        ('finance.manage', 'finance.delete'),
        ('finance_transactions.manage', 'finance_transactions.view'),
        ('finance_transactions.manage', 'finance_transactions.create'),
        ('finance_transactions.manage', 'finance_transactions.update'),
        ('finance_transactions.manage', 'finance_transactions.delete'),
        ('finance_accounts.manage', 'finance_accounts.view'),
        ('finance_accounts.manage', 'finance_accounts.create'),
        ('finance_accounts.manage', 'finance_accounts.update'),
        ('finance_accounts.manage', 'finance_accounts.delete'),
        ('finance_categories.manage', 'finance_categories.view'),
        ('finance_categories.manage', 'finance_categories.create'),
        ('finance_categories.manage', 'finance_categories.update'),
        ('finance_categories.manage', 'finance_categories.delete'),
        ('finance_transfers.manage', 'finance_transfers.view'),
        ('finance_transfers.manage', 'finance_transfers.create'),
        ('finance_transfers.manage', 'finance_transfers.update'),
        ('finance_transfers.manage', 'finance_transfers.delete'),
        ('finance_reconciliations.manage', 'finance_reconciliations.view'),
        ('finance_reconciliations.manage', 'finance_reconciliations.create'),
        ('finance_reconciliations.manage', 'finance_reconciliations.update'),
        ('finance_reconciliations.manage', 'finance_reconciliations.delete'),
        ('student_payments.manage', 'student_payments.view'),
        ('student_payments.manage', 'student_payments.create'),
        ('student_payments.manage', 'student_payments.update'),
        ('student_payments.manage', 'student_payments.delete'),
        ('referrals.manage', 'referrals.view'),
        ('referrals.manage', 'referrals.create'),
        ('referrals.manage', 'referrals.update'),
        ('referrals.manage', 'referrals.delete'),
        ('tournaments.manage', 'tournaments.view'),
        ('tournaments.manage', 'tournaments.create'),
        ('tournaments.manage', 'tournaments.update'),
        ('tournaments.manage', 'tournaments.delete'),
        ('events.manage', 'events.view'),
        ('events.manage', 'events.create'),
        ('events.manage', 'events.update'),
        ('events.manage', 'events.delete')
) AS expanded(source_permission, permission)
    ON expanded.source_permission = rp.permission
ON CONFLICT (role_id, permission) DO NOTHING;

-- Cross-module permissions that were previously implied by umbrella permissions in code.
INSERT INTO role_permissions (role_id, permission)
SELECT rp.role_id, expanded.permission
FROM role_permissions rp
JOIN (
    VALUES
        ('admissions.manage', 'enrollments.view'),
        ('admissions.manage', 'enrollments.create'),
        ('admissions.manage', 'enrollments.update'),
        ('admissions.manage', 'enrollments.delete'),
        ('admissions.manage', 'student_leaves.view'),
        ('admissions.manage', 'student_leaves.create'),
        ('admissions.manage', 'student_leaves.update'),
        ('admissions.manage', 'student_leaves.delete'),
        ('space_bookings.manage', 'games.view'),
        ('space_bookings.manage', 'games.create'),
        ('space_bookings.manage', 'games.update'),
        ('space_bookings.manage', 'games.delete'),
        ('space_bookings.manage', 'one_to_one.view'),
        ('space_bookings.manage', 'one_to_one.create'),
        ('space_bookings.manage', 'one_to_one.update'),
        ('space_bookings.manage', 'one_to_one.delete'),
        ('space_bookings.manage', 'one_to_one_bookings.view'),
        ('space_bookings.manage', 'one_to_one_bookings.create'),
        ('space_bookings.manage', 'one_to_one_bookings.update'),
        ('space_bookings.manage', 'one_to_one_bookings.delete'),
        ('finance.manage', 'finance_transactions.view'),
        ('finance.manage', 'finance_transactions.create'),
        ('finance.manage', 'finance_transactions.update'),
        ('finance.manage', 'finance_transactions.delete'),
        ('finance.manage', 'finance_accounts.view'),
        ('finance.manage', 'finance_accounts.create'),
        ('finance.manage', 'finance_accounts.update'),
        ('finance.manage', 'finance_accounts.delete'),
        ('finance.manage', 'finance_categories.view'),
        ('finance.manage', 'finance_categories.create'),
        ('finance.manage', 'finance_categories.update'),
        ('finance.manage', 'finance_categories.delete'),
        ('finance.manage', 'finance_transfers.view'),
        ('finance.manage', 'finance_transfers.create'),
        ('finance.manage', 'finance_transfers.update'),
        ('finance.manage', 'finance_transfers.delete'),
        ('finance.manage', 'finance_reconciliations.view'),
        ('finance.manage', 'finance_reconciliations.create'),
        ('finance.manage', 'finance_reconciliations.update'),
        ('finance.manage', 'finance_reconciliations.delete'),
        ('finance.manage', 'student_payments.view'),
        ('finance.manage', 'student_payments.create'),
        ('finance.manage', 'student_payments.update'),
        ('finance.manage', 'student_payments.delete'),
        ('finance.manage', 'referrals.view'),
        ('finance.manage', 'referrals.create'),
        ('finance.manage', 'referrals.update'),
        ('finance.manage', 'referrals.delete'),
        ('finance.manage', 'tournaments.view'),
        ('finance.manage', 'tournaments.create'),
        ('finance.manage', 'tournaments.update'),
        ('finance.manage', 'tournaments.delete'),
        ('finance.manage', 'finance.consolidated'),
        ('reports.view', 'reports.export')
) AS expanded(source_permission, permission)
    ON expanded.source_permission = rp.permission
ON CONFLICT (role_id, permission) DO NOTHING;
