BEGIN;

-- ============================================================
-- Staff work-time records
-- Source of truth for hourly payroll.
-- Multiple work periods may exist for one staff member/day.
-- ============================================================

CREATE TABLE staff_work_time_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    work_date DATE NOT NULL,
    clock_in TIME NOT NULL,
    clock_out TIME NOT NULL,
    break_minutes INTEGER NOT NULL DEFAULT 0,
    note TEXT NOT NULL DEFAULT '',
    recorded_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    -- If clock_out is earlier than clock_in, the work period ends
    -- on the following calendar day. Equal times are not valid.
    CHECK (clock_out <> clock_in),
    CHECK (break_minutes >= 0 AND break_minutes < 1440)
);

CREATE INDEX idx_staff_work_time_user_date
    ON staff_work_time_records(user_id, work_date);


-- ============================================================
-- Student enrollment status history
-- Preserves whether an enrollment was active for a historical
-- payroll period. effective_to is exclusive.
-- ============================================================

CREATE TABLE student_enrollment_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT NOT NULL
        REFERENCES student_enrollments(id) ON DELETE CASCADE,
    active INTEGER NOT NULL,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CHECK (active IN (0, 1)),
    CHECK (
        effective_to IS NULL
        OR effective_to > effective_from
    )
);

CREATE INDEX idx_enrollment_status_history_enrollment
    ON student_enrollment_status_history(enrollment_id);

CREATE INDEX idx_enrollment_status_history_dates
    ON student_enrollment_status_history(
        effective_from,
        effective_to
    );

CREATE UNIQUE INDEX idx_enrollment_status_history_open
    ON student_enrollment_status_history(enrollment_id)
    WHERE effective_to IS NULL;


-- ============================================================
-- Student group membership history
-- Preserves historical membership for payroll calculations.
-- effective_to NULL means currently assigned.
-- ============================================================

CREATE TABLE student_group_membership_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL
        REFERENCES student_groups(id) ON DELETE CASCADE,
    admission_id BIGINT NOT NULL
        REFERENCES admissions(id) ON DELETE CASCADE,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CHECK (
        effective_to IS NULL
        OR effective_to > effective_from
    )
);

CREATE INDEX idx_group_membership_history_group
    ON student_group_membership_history(group_id);

CREATE INDEX idx_group_membership_history_admission
    ON student_group_membership_history(admission_id);

CREATE INDEX idx_group_membership_history_dates
    ON student_group_membership_history(
        effective_from,
        effective_to
    );

CREATE UNIQUE INDEX idx_group_membership_history_open
    ON student_group_membership_history(group_id, admission_id)
    WHERE effective_to IS NULL;


-- ============================================================
-- Staff group assignment history
-- Preserves historical staff/group responsibility.
-- ============================================================

CREATE TABLE student_group_staff_assignment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL
        REFERENCES student_groups(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL
        REFERENCES users(id) ON DELETE CASCADE,
    assignment_role TEXT NOT NULL DEFAULT '',
    primary_assignment INTEGER NOT NULL DEFAULT 0,
    effective_from DATE NOT NULL,
    effective_to DATE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CHECK (primary_assignment IN (0, 1)),
    CHECK (
        effective_to IS NULL
        OR effective_to > effective_from
    )
);

CREATE INDEX idx_group_staff_history_group
    ON student_group_staff_assignment_history(group_id);

CREATE INDEX idx_group_staff_history_user
    ON student_group_staff_assignment_history(user_id);

CREATE INDEX idx_group_staff_history_dates
    ON student_group_staff_assignment_history(
        effective_from,
        effective_to
    );

CREATE UNIQUE INDEX idx_group_staff_history_open
    ON student_group_staff_assignment_history(group_id, user_id)
    WHERE effective_to IS NULL;


-- ============================================================
-- Backfill CURRENT relationships.
--
-- These dates represent when the history system was introduced,
-- not fabricated historical assignment dates.
-- ============================================================

INSERT INTO student_enrollment_status_history (
    enrollment_id,
    active,
    effective_from,
    effective_to,
    created_at,
    updated_at
)
SELECT
    se.id,
    COALESCE(se.active, 1),
    CASE
        WHEN COALESCE(se.active, 1) = 1
        THEN COALESCE(se.enrollment_date, CURRENT_DATE)
        ELSE CURRENT_DATE
    END,
    NULL,
    NOW(),
    NOW()
FROM student_enrollments se
ON CONFLICT DO NOTHING;


INSERT INTO student_group_membership_history (
    group_id,
    admission_id,
    effective_from,
    effective_to,
    created_at,
    updated_at
)
SELECT
    sgm.group_id,
    sgm.admission_id,
    CURRENT_DATE,
    NULL,
    NOW(),
    NOW()
FROM student_group_members sgm
ON CONFLICT DO NOTHING;


INSERT INTO student_group_staff_assignment_history (
    group_id,
    user_id,
    assignment_role,
    primary_assignment,
    effective_from,
    effective_to,
    created_at,
    updated_at
)
SELECT
    sgs.group_id,
    sgs.user_id,
    COALESCE(sgs.assignment_role, ''),
    COALESCE(sgs.primary_assignment, 0),
    CURRENT_DATE,
    NULL,
    NOW(),
    NOW()
FROM student_group_staff sgs
ON CONFLICT DO NOTHING;


-- Legacy coach relationships may still exist without a matching
-- canonical student_group_staff row. Preserve those assignments too.
INSERT INTO student_group_staff_assignment_history (
    group_id,
    user_id,
    assignment_role,
    primary_assignment,
    effective_from,
    effective_to,
    created_at,
    updated_at
)
SELECT
    sgc.group_id,
    sgc.user_id,
    'coach',
    0,
    CURRENT_DATE,
    NULL,
    NOW(),
    NOW()
FROM student_group_coaches sgc
ON CONFLICT DO NOTHING;

COMMIT;
