-- Mekmaa PostgreSQL initial schema
-- Generated from the final SQLite schema.
--
-- PostgreSQL migration policy:
--   * tables are dependency ordered for foreign-key creation
--   * SQLite AUTOINCREMENT becomes PostgreSQL identity
--   * SQLite REAL becomes PostgreSQL NUMERIC
--   * SQLite DATETIME becomes PostgreSQL TIMESTAMPTZ
--   * integer 0/1 flags intentionally remain integers for first cutover
--
-- Historical SQLite migrations remain separate.


-- table: admission_pricing
CREATE TABLE admission_pricing (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			practice_type TEXT NOT NULL UNIQUE,
			price NUMERIC NOT NULL DEFAULT 0,
			monthly_fee NUMERIC NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: admissions
CREATE TABLE admissions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			student_id TEXT NOT NULL UNIQUE,
			full_name TEXT NOT NULL,
			admission_date TEXT NOT NULL,
			date_of_birth TEXT NOT NULL,
			gender TEXT NOT NULL,
			practice_type TEXT NOT NULL DEFAULT 'group_practice',
			address TEXT NOT NULL,
			passport_number TEXT NOT NULL,
			school TEXT NOT NULL,
			guardian_name TEXT NOT NULL,
			guardian_relationship TEXT NOT NULL,
			guardian_contact_number TEXT NOT NULL,
			guardian_alternative_contact_number TEXT NOT NULL,
			medical_information TEXT NOT NULL,
			free_admission INTEGER NOT NULL DEFAULT 0,
			free_monthly_fee INTEGER NOT NULL DEFAULT 0,
			payment_collected INTEGER NOT NULL DEFAULT 0,
			payment_collected_at TIMESTAMPTZ,
			admission_payment_amount NUMERIC NOT NULL DEFAULT 0,
			finance_transaction_id INTEGER,
			training_program_id INTEGER,
			photo_path TEXT NOT NULL DEFAULT '',
			qr_code_path TEXT NOT NULL DEFAULT '',
			qr_code_value TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		, payment_void_reason TEXT NOT NULL DEFAULT '', payment_voided_by_user_id INTEGER, payment_voided_at TIMESTAMPTZ);

-- table: courts
CREATE TABLE courts (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			code TEXT NOT NULL UNIQUE,
			description TEXT NOT NULL DEFAULT '',
			active INTEGER NOT NULL DEFAULT 1,
			sort_order INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: divisions
CREATE TABLE divisions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			code TEXT NOT NULL UNIQUE,
			slug TEXT NOT NULL UNIQUE,
			name TEXT NOT NULL,
			description TEXT NOT NULL DEFAULT '',
			active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: events
CREATE TABLE events (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			title TEXT NOT NULL,
			category TEXT NOT NULL,
			event_date TEXT NOT NULL,
			start_time TEXT,
			end_time TEXT,
			registration_deadline TEXT,
			venue TEXT NOT NULL,
			summary TEXT NOT NULL,
			image_path TEXT NOT NULL DEFAULT '',
			cta_label TEXT NOT NULL DEFAULT '',
			cta_link TEXT NOT NULL DEFAULT '',
			published INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		, game_id INTEGER NOT NULL DEFAULT 0);

-- table: finance_accounts
CREATE TABLE finance_accounts (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			division_id INTEGER,
			account_code TEXT NOT NULL DEFAULT '',
			name TEXT NOT NULL,
			account_type TEXT NOT NULL,
			description TEXT NOT NULL DEFAULT '',
			opening_balance NUMERIC NOT NULL DEFAULT 0,
			is_system INTEGER NOT NULL DEFAULT 0,
			is_active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			created_by_user_id INTEGER,
			updated_by_user_id INTEGER
		);

-- table: finance_categories
CREATE TABLE finance_categories (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			code TEXT NOT NULL UNIQUE,
			name TEXT NOT NULL,
			direction TEXT NOT NULL,
			active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: finance_operation_keys
CREATE TABLE finance_operation_keys (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			operation_scope TEXT NOT NULL,
			user_id INTEGER NOT NULL DEFAULT 0,
			fingerprint TEXT NOT NULL,
			result_ref TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL,
			UNIQUE(operation_scope, user_id, fingerprint)
		);

-- table: finance_transactions
CREATE TABLE finance_transactions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			receipt_number TEXT NOT NULL UNIQUE,
			category TEXT NOT NULL,
			reference_type TEXT NOT NULL,
			reference_id INTEGER,
			person_name TEXT NOT NULL,
			description TEXT NOT NULL,
			payment_method TEXT NOT NULL DEFAULT 'cash',
			amount NUMERIC NOT NULL DEFAULT 0,
			recorded_by_user_id INTEGER,
			recorded_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ NOT NULL
		, division_id INTEGER, finance_account_id INTEGER, approval_status TEXT NOT NULL DEFAULT 'approved', approved_by_user_id INTEGER, approved_at TIMESTAMPTZ, transaction_type TEXT NOT NULL DEFAULT 'income', source_type TEXT NOT NULL DEFAULT '', source_id INTEGER, transfer_group_id TEXT NOT NULL DEFAULT '', reference_number TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', voided_at TIMESTAMPTZ, voided_by_user_id INTEGER, void_reason TEXT NOT NULL DEFAULT '', updated_at TIMESTAMPTZ);

-- table: games
CREATE TABLE games (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL UNIQUE,
			activity TEXT NOT NULL UNIQUE,
			description TEXT NOT NULL DEFAULT '',
			active INTEGER NOT NULL DEFAULT 1,
			sort_order INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: one_to_one_offerings
CREATE TABLE one_to_one_offerings (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			game TEXT NOT NULL,
			audience TEXT NOT NULL,
			occurrence TEXT NOT NULL DEFAULT 'per_day',
			session_count INTEGER NOT NULL DEFAULT 1,
			price NUMERIC NOT NULL DEFAULT 0,
			active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: pricing_rules
CREATE TABLE pricing_rules (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			activity TEXT NOT NULL,
			quantity INTEGER NOT NULL,
			weekday_offpeak_price NUMERIC NOT NULL DEFAULT 0,
			weekday_peak_price NUMERIC NOT NULL DEFAULT 0,
			weekend_offpeak_price NUMERIC NOT NULL DEFAULT 0,
			weekend_peak_price NUMERIC NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		, game_id INTEGER NOT NULL DEFAULT 0);

-- table: pricing_settings
CREATE TABLE pricing_settings (
			id BIGINT PRIMARY KEY,
			peak_start_hour TEXT NOT NULL,
			peak_end_hour TEXT NOT NULL,
			referral_commission_amount NUMERIC NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: receipt_sequences
CREATE TABLE receipt_sequences (
			scope TEXT NOT NULL,
			year INTEGER NOT NULL,
			next_value INTEGER NOT NULL DEFAULT 1,
			PRIMARY KEY (scope, year)
		);

-- table: referral_partners
CREATE TABLE referral_partners (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			code TEXT NOT NULL UNIQUE,
			email TEXT NOT NULL DEFAULT '',
			phone TEXT NOT NULL,
			active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: roles
CREATE TABLE roles (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL UNIQUE
		);

-- table: space_schedules
CREATE TABLE space_schedules (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			slot_date TEXT NOT NULL,
			slot_hour TEXT NOT NULL,
			entry_type TEXT NOT NULL,
			activity TEXT NOT NULL,
			quantity INTEGER NOT NULL,
			title TEXT NOT NULL,
			notes TEXT NOT NULL,
			status TEXT NOT NULL DEFAULT 'confirmed',
			requester_name TEXT NOT NULL DEFAULT '',
			requester_email TEXT NOT NULL DEFAULT '',
			requester_phone TEXT NOT NULL DEFAULT '',
			requested_by_user_id INTEGER,
			review_note TEXT NOT NULL DEFAULT '',
			customer_message TEXT NOT NULL DEFAULT '',
			status_changed_at TIMESTAMPTZ,
			status_changed_by_user_id INTEGER,
			status_change_source TEXT NOT NULL DEFAULT '',
			cancellation_reason TEXT NOT NULL DEFAULT '',
			cancellation_finance_note TEXT NOT NULL DEFAULT '',
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL
		);

-- table: training_programs
CREATE TABLE training_programs (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			activity TEXT NOT NULL,
			training_format TEXT NOT NULL,
			admission_fee NUMERIC NOT NULL DEFAULT 0,
			monthly_fee NUMERIC NOT NULL DEFAULT 0,
			active INTEGER NOT NULL DEFAULT 1,
			sort_order INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL, division_id INTEGER, game_id INTEGER NOT NULL DEFAULT 0,
			UNIQUE(activity, training_format)
		);

-- table: users
CREATE TABLE users (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email TEXT NOT NULL UNIQUE,
			name TEXT NOT NULL,
			password_hash TEXT NOT NULL,
			created_at TIMESTAMPTZ NOT NULL
		, email_verified_at TIMESTAMPTZ);

-- table: admission_training_programs
CREATE TABLE admission_training_programs (
			admission_id INTEGER NOT NULL,
			training_program_id INTEGER NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			PRIMARY KEY (admission_id, training_program_id),
			FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE,
			FOREIGN KEY (training_program_id) REFERENCES training_programs(id)
		);

-- table: booking_access_tokens
CREATE TABLE booking_access_tokens (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL,
			public_id TEXT NOT NULL,
			token_hash TEXT NOT NULL UNIQUE,
			purpose TEXT NOT NULL DEFAULT 'status',
			active INTEGER NOT NULL DEFAULT 1,
			expires_at TIMESTAMPTZ NOT NULL,
			last_accessed_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL,
			revoked_at TIMESTAMPTZ,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE
		);

-- table: booking_communications
CREATE TABLE booking_communications (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL,
			event_type TEXT NOT NULL,
			related_event_type TEXT NOT NULL DEFAULT '',
			event_key TEXT NOT NULL,
			channel TEXT NOT NULL,
			recipient TEXT NOT NULL,
			subject TEXT NOT NULL DEFAULT '',
			body_preview TEXT NOT NULL DEFAULT '',
			status TEXT NOT NULL DEFAULT 'pending',
			provider TEXT NOT NULL DEFAULT '',
			provider_message TEXT NOT NULL DEFAULT '',
			attempt_count INTEGER NOT NULL DEFAULT 0,
			last_attempt_at TIMESTAMPTZ,
			sent_at TIMESTAMPTZ,
			created_at TIMESTAMPTZ NOT NULL,
			created_by_user_id INTEGER,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE,
			FOREIGN KEY (created_by_user_id) REFERENCES users(id)
		);

-- table: booking_financials
CREATE TABLE booking_financials (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL UNIQUE,
			quoted_amount NUMERIC NOT NULL DEFAULT 0,
			paid INTEGER NOT NULL DEFAULT 0,
			paid_at TIMESTAMPTZ,
			payment_method TEXT NOT NULL DEFAULT '',
			finance_transaction_id INTEGER,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE,
			FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(id)
		);

-- table: booking_payment_collections
CREATE TABLE booking_payment_collections (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL,
			finance_transaction_id INTEGER NOT NULL UNIQUE,
			amount NUMERIC NOT NULL DEFAULT 0,
			payment_method TEXT NOT NULL DEFAULT 'cash',
			payment_note TEXT NOT NULL DEFAULT '',
			collected_by_user_id INTEGER,
			collected_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			voided INTEGER NOT NULL DEFAULT 0,
			void_reason TEXT NOT NULL DEFAULT '',
			voided_by_user_id INTEGER,
			voided_at TIMESTAMPTZ,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE,
			FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(id),
			FOREIGN KEY (collected_by_user_id) REFERENCES users(id),
			FOREIGN KEY (voided_by_user_id) REFERENCES users(id)
		);

-- table: booking_referrals
CREATE TABLE booking_referrals (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL UNIQUE,
			partner_id INTEGER NOT NULL,
			commission_amount NUMERIC NOT NULL,
			paid INTEGER NOT NULL DEFAULT 0,
			paid_at TIMESTAMPTZ,
			payment_method TEXT NOT NULL DEFAULT '',
			finance_transaction_id INTEGER,
			created_at TIMESTAMPTZ NOT NULL, void_reason TEXT NOT NULL DEFAULT '', voided_by_user_id INTEGER, voided_at TIMESTAMPTZ,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE,
			FOREIGN KEY (partner_id) REFERENCES referral_partners(id)
		);

-- table: booking_request_changes
CREATE TABLE booking_request_changes (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL,
			previous_slot_date TEXT NOT NULL,
			previous_slot_hour TEXT NOT NULL,
			previous_activity TEXT NOT NULL,
			previous_quantity INTEGER NOT NULL,
			previous_quoted_price NUMERIC NOT NULL DEFAULT 0,
			new_slot_date TEXT NOT NULL,
			new_slot_hour TEXT NOT NULL,
			new_activity TEXT NOT NULL,
			new_quantity INTEGER NOT NULL,
			new_quoted_price NUMERIC NOT NULL DEFAULT 0,
			action_type TEXT NOT NULL,
			previous_status TEXT NOT NULL DEFAULT '',
			new_status TEXT NOT NULL DEFAULT '',
			change_source TEXT NOT NULL DEFAULT '',
			finance_note TEXT NOT NULL DEFAULT '',
			review_note TEXT NOT NULL DEFAULT '',
			customer_message TEXT NOT NULL DEFAULT '',
			changed_by_user_id INTEGER,
			changed_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE,
			FOREIGN KEY (changed_by_user_id) REFERENCES users(id)
		);

-- table: cash_reconciliations
CREATE TABLE cash_reconciliations (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			finance_account_id INTEGER NOT NULL,
			reconciliation_date TEXT NOT NULL,
			expected_balance NUMERIC NOT NULL DEFAULT 0,
			counted_balance NUMERIC NOT NULL DEFAULT 0,
			difference NUMERIC NOT NULL DEFAULT 0,
			notes TEXT NOT NULL DEFAULT '',
			status TEXT NOT NULL DEFAULT 'balanced',
			reconciled_by_user_id INTEGER,
			void_reason TEXT NOT NULL DEFAULT '',
			voided_by_user_id INTEGER,
			voided_at TIMESTAMPTZ,
			superseded_by_reconciliation_id INTEGER,
			created_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (finance_account_id) REFERENCES finance_accounts(id),
			FOREIGN KEY (reconciled_by_user_id) REFERENCES users(id),
			FOREIGN KEY (voided_by_user_id) REFERENCES users(id),
			FOREIGN KEY (superseded_by_reconciliation_id) REFERENCES cash_reconciliations(id)
		);

-- table: coach_attendance_records
CREATE TABLE coach_attendance_records (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id INTEGER NOT NULL,
			attendance_date TEXT NOT NULL,
			status TEXT NOT NULL,
			note TEXT NOT NULL DEFAULT '',
			recorded_by_user_id INTEGER,
			recorded_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
			FOREIGN KEY (recorded_by_user_id) REFERENCES users(id)
		);

-- table: coach_profiles
CREATE TABLE coach_profiles (
			user_id BIGINT PRIMARY KEY,
			phone TEXT NOT NULL DEFAULT '',
			address TEXT NOT NULL DEFAULT '',
			specialties TEXT NOT NULL DEFAULT '',
			notes TEXT NOT NULL DEFAULT '',
			active INTEGER NOT NULL DEFAULT 1,
			coach_type TEXT NOT NULL DEFAULT 'main',
			parent_coach_id INTEGER,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
			FOREIGN KEY (parent_coach_id) REFERENCES users(id)
		);

-- table: court_activities
CREATE TABLE court_activities (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			court_id INTEGER NOT NULL,
			activity TEXT NOT NULL,
			display_name TEXT NOT NULL,
			max_quantity INTEGER NOT NULL DEFAULT 1,
			auto_accept INTEGER NOT NULL DEFAULT 0,
			active INTEGER NOT NULL DEFAULT 1,
			sort_order INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL, game_id INTEGER NOT NULL DEFAULT 0,
			UNIQUE(court_id, activity),
			FOREIGN KEY (court_id) REFERENCES courts(id) ON DELETE CASCADE
		);

-- table: court_closures
CREATE TABLE court_closures (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	court_id INTEGER NOT NULL,
	closure_date TEXT NOT NULL,
	start_hour TEXT NOT NULL,
	end_hour TEXT NOT NULL,
	activity TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL,
	reason TEXT NOT NULL DEFAULT '',
	active INTEGER NOT NULL DEFAULT 1,
	created_at TIMESTAMPTZ NOT NULL,
	updated_at TIMESTAMPTZ NOT NULL,
	FOREIGN KEY (court_id) REFERENCES courts(id) ON DELETE CASCADE
);

-- table: court_layouts
CREATE TABLE court_layouts (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			court_id INTEGER NOT NULL,
			name TEXT NOT NULL,
			description TEXT NOT NULL DEFAULT '',
			active INTEGER NOT NULL DEFAULT 1,
			sort_order INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			UNIQUE(court_id, name),
			FOREIGN KEY (court_id) REFERENCES courts(id) ON DELETE CASCADE
		);

-- table: email_verifications
CREATE TABLE email_verifications (
			user_id BIGINT PRIMARY KEY,
			otp_hash TEXT NOT NULL,
			expires_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
		);

-- table: finance_period_locks
CREATE TABLE finance_period_locks (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			locked_until TEXT,
			notes TEXT NOT NULL DEFAULT '',
			updated_by_user_id INTEGER,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
		);

-- table: one_to_one_bookings
CREATE TABLE one_to_one_bookings (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL UNIQUE,
			offering_id INTEGER NOT NULL,
			customer_name TEXT NOT NULL,
			offering_name TEXT NOT NULL,
			game TEXT NOT NULL,
			audience TEXT NOT NULL,
			price NUMERIC NOT NULL DEFAULT 0,
			discounted_price NUMERIC NOT NULL DEFAULT -1,
			coach_fee NUMERIC NOT NULL DEFAULT 0,
			sessions INTEGER NOT NULL DEFAULT 1,
			occurrence TEXT NOT NULL DEFAULT 'per_day',
			max_sessions INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE,
			FOREIGN KEY (offering_id) REFERENCES one_to_one_offerings(id)
		);

-- table: role_permissions
CREATE TABLE role_permissions (
			role_id INTEGER NOT NULL,
			permission TEXT NOT NULL,
			PRIMARY KEY (role_id, permission),
			FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
		);

-- table: sessions
CREATE TABLE sessions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			user_id INTEGER NOT NULL,
			token_hash TEXT NOT NULL UNIQUE,
			expires_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
		);

-- table: student_enrollments
CREATE TABLE student_enrollments (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			admission_id INTEGER NOT NULL,
			training_program_id INTEGER NOT NULL,
			free_admission INTEGER NOT NULL DEFAULT 0,
			free_monthly_fee INTEGER NOT NULL DEFAULT 0,
			payment_collected INTEGER NOT NULL DEFAULT 0,
			payment_collected_at TIMESTAMPTZ,
			admission_payment_amount NUMERIC NOT NULL DEFAULT 0,
			finance_transaction_id INTEGER,
			active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			UNIQUE(admission_id, training_program_id),
			FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE,
			FOREIGN KEY (training_program_id) REFERENCES training_programs(id),
			FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(id)
		);

-- table: student_groups
CREATE TABLE student_groups (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name TEXT NOT NULL,
			code TEXT NOT NULL UNIQUE,
			description TEXT NOT NULL,
			training_program_id INTEGER,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (training_program_id) REFERENCES training_programs(id)
		);

-- table: user_divisions
CREATE TABLE user_divisions (
			user_id INTEGER NOT NULL,
			division_id INTEGER NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			PRIMARY KEY (user_id, division_id),
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
			FOREIGN KEY (division_id) REFERENCES divisions(id)
		);

-- table: user_roles
CREATE TABLE user_roles (
			user_id INTEGER NOT NULL,
			role_id INTEGER NOT NULL,
			PRIMARY KEY (user_id, role_id),
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
			FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
		);

-- table: booking_cancellation_requests
CREATE TABLE booking_cancellation_requests (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			schedule_id INTEGER NOT NULL,
			status TEXT NOT NULL DEFAULT 'pending',
			request_reason TEXT NOT NULL DEFAULT '',
			requested_at TIMESTAMPTZ NOT NULL,
			token_id INTEGER,
			review_note TEXT NOT NULL DEFAULT '',
			reviewed_at TIMESTAMPTZ,
			reviewed_by_user_id INTEGER,
			FOREIGN KEY (schedule_id) REFERENCES space_schedules(id) ON DELETE CASCADE,
			FOREIGN KEY (token_id) REFERENCES booking_access_tokens(id),
			FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id)
		);

-- table: court_layout_items
CREATE TABLE court_layout_items (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			layout_id INTEGER NOT NULL,
			activity TEXT NOT NULL,
			quantity INTEGER NOT NULL,
			UNIQUE(layout_id, activity),
			FOREIGN KEY (layout_id) REFERENCES court_layouts(id) ON DELETE CASCADE
		);

-- table: student_enrollment_leaves
CREATE TABLE student_enrollment_leaves (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			enrollment_id INTEGER NOT NULL,
			start_date TEXT NOT NULL,
			end_date TEXT NOT NULL,
			reason TEXT NOT NULL DEFAULT '',
			active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (enrollment_id) REFERENCES student_enrollments(id) ON DELETE CASCADE
		);

-- table: student_group_coaches
CREATE TABLE student_group_coaches (
			group_id INTEGER NOT NULL,
			user_id INTEGER NOT NULL,
			created_at TIMESTAMPTZ NOT NULL,
			PRIMARY KEY (group_id, user_id),
			FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
		);

-- table: student_group_members
CREATE TABLE student_group_members (
			group_id INTEGER NOT NULL,
			admission_id INTEGER NOT NULL,
			PRIMARY KEY (group_id, admission_id),
			FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
			FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE
		);

-- table: student_group_sessions
CREATE TABLE student_group_sessions (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			group_id INTEGER NOT NULL,
			title TEXT NOT NULL,
			day_of_week TEXT NOT NULL,
			start_time TEXT NOT NULL,
			end_time TEXT NOT NULL,
			active INTEGER NOT NULL DEFAULT 1,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE
		);

-- table: student_group_staff
CREATE TABLE student_group_staff (
			group_id INTEGER NOT NULL,
			user_id INTEGER NOT NULL,
			assignment_role TEXT NOT NULL,
			primary_assignment INTEGER NOT NULL DEFAULT 0,
			created_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			PRIMARY KEY (group_id, user_id, assignment_role),
			FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
			FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
		);

-- table: student_monthly_payments
CREATE TABLE student_monthly_payments (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			admission_id INTEGER NOT NULL,
			enrollment_id INTEGER,
			payment_month TEXT NOT NULL,
			amount NUMERIC NOT NULL DEFAULT 0,
			payment_method TEXT NOT NULL DEFAULT 'cash',
			finance_transaction_id INTEGER NOT NULL,
			collected_by_user_id INTEGER,
			collected_at TIMESTAMPTZ NOT NULL,
			created_at TIMESTAMPTZ NOT NULL, voided INTEGER NOT NULL DEFAULT 0, void_reason TEXT NOT NULL DEFAULT '', voided_by_user_id INTEGER, voided_at TIMESTAMPTZ,
			FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE,
			FOREIGN KEY (enrollment_id) REFERENCES student_enrollments(id) ON DELETE CASCADE,
			FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(id)
		);

-- table: attendance_records
CREATE TABLE attendance_records (
			id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			group_id INTEGER NOT NULL,
			session_id INTEGER,
			admission_id INTEGER NOT NULL,
			attendance_date TEXT NOT NULL,
			status TEXT NOT NULL,
			note TEXT NOT NULL DEFAULT '',
			recorded_by_user_id INTEGER,
			recorded_at TIMESTAMPTZ NOT NULL,
			updated_at TIMESTAMPTZ NOT NULL,
			FOREIGN KEY (group_id) REFERENCES student_groups(id) ON DELETE CASCADE,
			FOREIGN KEY (session_id) REFERENCES student_group_sessions(id) ON DELETE CASCADE,
			FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE,
			FOREIGN KEY (recorded_by_user_id) REFERENCES users(id)
		);

-- indexes and remaining schema objects
CREATE INDEX idx_student_group_staff_user
			ON student_group_staff(user_id);
CREATE INDEX idx_student_group_staff_group
			ON student_group_staff(group_id);






























CREATE INDEX idx_sessions_token_hash ON sessions(token_hash);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);
CREATE INDEX idx_role_permissions_role_id ON role_permissions(role_id);
CREATE INDEX idx_email_verifications_expires_at ON email_verifications(expires_at);
CREATE INDEX idx_admissions_created_at ON admissions(created_at);
CREATE INDEX idx_admission_training_programs_admission_id ON admission_training_programs(admission_id);
CREATE INDEX idx_admission_training_programs_program_id ON admission_training_programs(training_program_id);
CREATE INDEX idx_student_enrollments_admission_id ON student_enrollments(admission_id);
CREATE INDEX idx_student_enrollments_program_id ON student_enrollments(training_program_id);
CREATE INDEX idx_student_enrollments_active ON student_enrollments(active, admission_id);
CREATE INDEX idx_student_enrollment_leaves_enrollment_dates ON student_enrollment_leaves(enrollment_id, active, start_date, end_date);
CREATE INDEX idx_student_groups_created_at ON student_groups(created_at);
CREATE INDEX idx_student_group_members_group_id ON student_group_members(group_id);
CREATE INDEX idx_student_group_members_admission_id ON student_group_members(admission_id);
CREATE INDEX idx_student_group_sessions_group_id ON student_group_sessions(group_id, active, day_of_week, start_time);
CREATE INDEX idx_coach_profiles_active ON coach_profiles(active);
CREATE INDEX idx_coach_profiles_parent ON coach_profiles(parent_coach_id);
CREATE UNIQUE INDEX idx_coach_attendance_user_date ON coach_attendance_records(user_id, attendance_date);
CREATE INDEX idx_coach_attendance_date ON coach_attendance_records(attendance_date);
CREATE INDEX idx_attendance_group_date ON attendance_records(group_id, attendance_date);
CREATE INDEX idx_courts_active_order
		ON courts(active, sort_order, name);
CREATE INDEX idx_court_activities_court
		ON court_activities(court_id, active, sort_order);
CREATE INDEX idx_court_layouts_court
		ON court_layouts(court_id, active, sort_order);
CREATE INDEX idx_court_layout_items_layout
		ON court_layout_items(layout_id);
CREATE INDEX idx_court_closures_date
ON court_closures(closure_date, start_hour, end_hour);
CREATE INDEX idx_court_closures_court
ON court_closures(court_id, active, closure_date);
CREATE INDEX idx_court_closures_activity
ON court_closures(activity, active, closure_date);
CREATE UNIQUE INDEX idx_pricing_rules_option ON pricing_rules(activity, quantity);
CREATE UNIQUE INDEX idx_admission_pricing_type ON admission_pricing(practice_type);
CREATE INDEX idx_finance_transactions_recorded_at ON finance_transactions(recorded_at);
CREATE INDEX idx_finance_transactions_reference ON finance_transactions(reference_type, reference_id);
CREATE INDEX idx_admissions_finance_transaction_id ON admissions(finance_transaction_id);
CREATE INDEX idx_student_monthly_payments_finance_transaction_id ON student_monthly_payments(finance_transaction_id);
CREATE INDEX idx_student_monthly_payments_month ON student_monthly_payments(payment_month, collected_at);
CREATE INDEX idx_events_date ON events(event_date, start_time);
CREATE INDEX idx_events_published ON events(published, event_date);
CREATE INDEX idx_games_active_order ON games(active, sort_order, name);
CREATE INDEX idx_space_schedules_slot ON space_schedules(slot_date, slot_hour);
CREATE INDEX idx_booking_referrals_partner ON booking_referrals(partner_id, paid);
CREATE INDEX idx_booking_financials_paid ON booking_financials(paid, schedule_id);
CREATE INDEX idx_one_to_one_offerings_active ON one_to_one_offerings(active, name, id);
CREATE INDEX idx_one_to_one_bookings_schedule ON one_to_one_bookings(schedule_id);
CREATE INDEX idx_one_to_one_bookings_slot_lookup ON one_to_one_bookings(offering_id, customer_name);
CREATE INDEX idx_booking_payment_collections_schedule ON booking_payment_collections(schedule_id, collected_at DESC, id DESC);
CREATE INDEX idx_booking_payment_collections_voided ON booking_payment_collections(voided, schedule_id);
CREATE INDEX idx_booking_request_changes_schedule ON booking_request_changes(schedule_id, changed_at DESC);
CREATE UNIQUE INDEX idx_booking_communications_event_channel ON booking_communications(event_key, channel);
CREATE INDEX idx_booking_communications_schedule ON booking_communications(schedule_id, created_at DESC);
CREATE INDEX idx_booking_communications_status ON booking_communications(status, created_at DESC);
CREATE INDEX idx_booking_communications_event_type ON booking_communications(event_type, created_at DESC);
CREATE INDEX idx_booking_communications_created_at ON booking_communications(created_at DESC);
CREATE INDEX idx_booking_access_tokens_schedule ON booking_access_tokens(schedule_id, active, expires_at DESC);
CREATE UNIQUE INDEX idx_booking_access_tokens_public_id ON booking_access_tokens(public_id);
CREATE INDEX idx_booking_cancellation_requests_schedule ON booking_cancellation_requests(schedule_id, status, requested_at DESC);
CREATE UNIQUE INDEX idx_booking_cancellation_requests_pending ON booking_cancellation_requests(schedule_id) WHERE status = 'pending';
CREATE INDEX idx_training_programs_active
		ON training_programs(active);
CREATE INDEX idx_training_programs_sort_order
		ON training_programs(sort_order, name);


CREATE INDEX idx_user_divisions_division_user ON user_divisions(division_id, user_id);
CREATE INDEX idx_training_programs_division_active ON training_programs(division_id, active, sort_order, id);
CREATE INDEX idx_finance_transactions_division_recorded ON finance_transactions(division_id, recorded_at DESC, id DESC);
CREATE INDEX idx_admissions_training_program_id
		ON admissions(training_program_id)
	;
CREATE INDEX idx_student_groups_training_program_id ON student_groups(training_program_id);
CREATE UNIQUE INDEX idx_attendance_group_session_student_date ON attendance_records(group_id, COALESCE(session_id, 0), admission_id, attendance_date);
CREATE INDEX idx_attendance_admission_month ON attendance_records(admission_id, attendance_date, status);
CREATE INDEX idx_admissions_qr_code_value ON admissions(qr_code_value);
CREATE UNIQUE INDEX idx_student_monthly_payment_student_month ON student_monthly_payments(admission_id, payment_month) WHERE enrollment_id IS NULL;
CREATE UNIQUE INDEX idx_student_monthly_payment_enrollment_month ON student_monthly_payments(enrollment_id, payment_month) WHERE enrollment_id IS NOT NULL;
CREATE INDEX idx_space_schedules_status_changed_at ON space_schedules(status, status_changed_at DESC);
CREATE INDEX idx_booking_request_changes_status ON booking_request_changes(schedule_id, action_type, changed_at DESC);
CREATE INDEX idx_admissions_admission_date ON admissions(admission_date);
CREATE INDEX idx_court_activities_game_id ON court_activities(game_id);
CREATE INDEX idx_pricing_rules_game_id ON pricing_rules(game_id);
CREATE INDEX idx_training_programs_game_id ON training_programs(game_id);
CREATE INDEX idx_events_game_id ON events(game_id);
CREATE INDEX idx_space_schedules_status ON space_schedules(status);
CREATE UNIQUE INDEX idx_admissions_student_id ON admissions(student_id);

CREATE INDEX idx_finance_accounts_type_active ON finance_accounts(account_type, is_active);

CREATE INDEX idx_cash_reconciliations_date ON cash_reconciliations(reconciliation_date DESC);


CREATE UNIQUE INDEX idx_cash_reconciliations_account_date_active ON cash_reconciliations(finance_account_id, reconciliation_date) WHERE voided_at IS NULL;
CREATE INDEX idx_finance_transactions_account ON finance_transactions(finance_account_id, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_transactions_approval ON finance_transactions(approval_status, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_transactions_type ON finance_transactions(transaction_type, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_transactions_status ON finance_transactions(voided_at, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_transactions_source ON finance_transactions(source_type, source_id);
CREATE INDEX idx_finance_transactions_transfer_group ON finance_transactions(transfer_group_id);
CREATE UNIQUE INDEX idx_finance_transactions_source_admission ON finance_transactions(source_type, source_id) WHERE source_type = 'admission';
CREATE UNIQUE INDEX idx_finance_transactions_source_student_monthly_payment ON finance_transactions(source_type, source_id) WHERE source_type = 'student_monthly_payment';
CREATE UNIQUE INDEX idx_finance_transactions_source_booking_payment_collection ON finance_transactions(source_type, source_id) WHERE source_type = 'booking_payment_collection';
CREATE UNIQUE INDEX idx_finance_transactions_source_booking_referral_payment ON finance_transactions(source_type, source_id) WHERE source_type = 'booking_referral_payment';
CREATE INDEX idx_finance_accounts_division_type_active ON finance_accounts(division_id, account_type, is_active, id);
CREATE UNIQUE INDEX idx_finance_accounts_division_name_ci ON finance_accounts(division_id, LOWER(name));
CREATE UNIQUE INDEX idx_finance_accounts_division_code_ci ON finance_accounts(division_id, UPPER(account_code)) WHERE TRIM(COALESCE(account_code, '')) <> '';
CREATE INDEX idx_finance_transactions_division_account ON finance_transactions(division_id, finance_account_id, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_accounts_division_name ON finance_accounts(division_id, name);
CREATE INDEX idx_finance_accounts_division_code ON finance_accounts(division_id, account_code);
CREATE INDEX idx_cash_reconciliations_account_voided ON cash_reconciliations(finance_account_id, voided_at, reconciliation_date DESC);
CREATE INDEX idx_finance_accounts_division_active ON finance_accounts(division_id, is_active, id);
CREATE INDEX idx_finance_accounts_lookup ON finance_accounts(division_id, LOWER(name), UPPER(account_code));
CREATE INDEX idx_finance_accounts_system ON finance_accounts(division_id, is_system, is_active);
CREATE INDEX idx_finance_transactions_account_division ON finance_transactions(finance_account_id, division_id, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_accounts_division_id ON finance_accounts(division_id, id);
CREATE INDEX idx_finance_accounts_division_system_name ON finance_accounts(division_id, is_system, name);
CREATE INDEX idx_finance_accounts_division_account_type ON finance_accounts(division_id, account_type, id);
CREATE INDEX idx_finance_transactions_division_payment ON finance_transactions(division_id, payment_method, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_transactions_division_type_account ON finance_transactions(division_id, transaction_type, finance_account_id, recorded_at DESC, id DESC);
CREATE INDEX idx_finance_accounts_division_created ON finance_accounts(division_id, created_at DESC, id DESC);
CREATE INDEX idx_finance_accounts_division_updated ON finance_accounts(division_id, updated_at DESC, id DESC);
CREATE INDEX idx_finance_accounts_division_description ON finance_accounts(division_id, description);
CREATE INDEX idx_finance_accounts_division_opening ON finance_accounts(division_id, opening_balance);
CREATE INDEX idx_finance_accounts_division_flags ON finance_accounts(division_id, is_system, is_active, account_type);
CREATE INDEX idx_finance_accounts_division_name_id ON finance_accounts(division_id, name, id);
CREATE INDEX idx_finance_accounts_division_code_id ON finance_accounts(division_id, account_code, id);
CREATE INDEX idx_finance_accounts_division_type_name ON finance_accounts(division_id, account_type, name);
