CREATE TABLE staff_salary_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    division_id BIGINT
        REFERENCES divisions(id)
        ON DELETE RESTRICT,

    training_program_id BIGINT
        REFERENCES training_programs(id)
        ON DELETE RESTRICT,

    compensation_type TEXT NOT NULL,

    rate NUMERIC(14,2) NOT NULL DEFAULT 0,

    student_basis TEXT NOT NULL DEFAULT 'active_enrollment',

    effective_from TEXT NOT NULL,
    effective_to TEXT NOT NULL DEFAULT '',

    active INTEGER NOT NULL DEFAULT 1,

    notes TEXT NOT NULL DEFAULT '',

    created_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    updated_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT staff_salary_profiles_type_check
        CHECK (
            compensation_type IN (
                'hourly',
                'weekly',
                'monthly',
                'per_student'
            )
        ),

    CONSTRAINT staff_salary_profiles_rate_check
        CHECK (rate >= 0),

    CONSTRAINT staff_salary_profiles_active_check
        CHECK (active IN (0, 1)),

    CONSTRAINT staff_salary_profiles_student_basis_check
        CHECK (
            student_basis IN (
                'active_enrollment',
                'group_membership',
                'attendance'
            )
        )
);

CREATE INDEX idx_staff_salary_profiles_user
    ON staff_salary_profiles(user_id);

CREATE INDEX idx_staff_salary_profiles_division
    ON staff_salary_profiles(division_id);

CREATE INDEX idx_staff_salary_profiles_training_program
    ON staff_salary_profiles(training_program_id);

CREATE INDEX idx_staff_salary_profiles_active
    ON staff_salary_profiles(active);

CREATE INDEX idx_staff_salary_profiles_effective
    ON staff_salary_profiles(effective_from, effective_to);
