CREATE TABLE IF NOT EXISTS tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    game_id INTEGER NOT NULL,
    participant_count INTEGER NOT NULL DEFAULT 0,
    entry_fee NUMERIC NOT NULL DEFAULT 0,
    tournament_date TEXT NOT NULL DEFAULT '',
    entry_fee_finance_transaction_id INTEGER,
    entry_fee_finance_account_id INTEGER,
    entry_fee_recorded_at TIMESTAMPTZ,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT tournaments_game_id_fkey FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT tournaments_entry_fee_finance_transaction_id_fkey FOREIGN KEY (entry_fee_finance_transaction_id) REFERENCES finance_transactions(id),
    CONSTRAINT tournaments_entry_fee_finance_account_id_fkey FOREIGN KEY (entry_fee_finance_account_id) REFERENCES finance_accounts(id)
);

CREATE TABLE IF NOT EXISTS tournament_sponsorships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL,
    sponsor_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    amount NUMERIC NOT NULL DEFAULT 0,
    finance_transaction_id INTEGER,
    finance_account_id INTEGER NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT tournament_sponsorships_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
    CONSTRAINT tournament_sponsorships_finance_transaction_id_fkey FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(id),
    CONSTRAINT tournament_sponsorships_finance_account_id_fkey FOREIGN KEY (finance_account_id) REFERENCES finance_accounts(id)
);

CREATE TABLE IF NOT EXISTS tournament_official_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL,
    person_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    amount NUMERIC NOT NULL DEFAULT 0,
    finance_transaction_id INTEGER,
    finance_account_id INTEGER NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT tournament_official_payments_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
    CONSTRAINT tournament_official_payments_finance_transaction_id_fkey FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(id),
    CONSTRAINT tournament_official_payments_finance_account_id_fkey FOREIGN KEY (finance_account_id) REFERENCES finance_accounts(id)
);

CREATE TABLE IF NOT EXISTS tournament_expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL,
    expense_type TEXT NOT NULL,
    item_name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    amount NUMERIC NOT NULL DEFAULT 0,
    finance_transaction_id INTEGER,
    finance_account_id INTEGER NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT tournament_expenses_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES tournaments(id) ON DELETE CASCADE,
    CONSTRAINT tournament_expenses_finance_transaction_id_fkey FOREIGN KEY (finance_transaction_id) REFERENCES finance_transactions(id),
    CONSTRAINT tournament_expenses_finance_account_id_fkey FOREIGN KEY (finance_account_id) REFERENCES finance_accounts(id)
);

CREATE INDEX IF NOT EXISTS idx_tournaments_date
    ON tournaments(tournament_date DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_tournaments_game
    ON tournaments(game_id, tournament_date DESC);

CREATE INDEX IF NOT EXISTS idx_tournament_sponsorships_tournament
    ON tournament_sponsorships(tournament_id, recorded_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_tournament_official_payments_tournament
    ON tournament_official_payments(tournament_id, recorded_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_tournament_expenses_tournament
    ON tournament_expenses(tournament_id, recorded_at DESC, id DESC);
