CREATE TABLE student_group_session_occurrences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    group_id BIGINT NOT NULL
        REFERENCES student_groups(id)
        ON DELETE CASCADE,

    timetable_session_id BIGINT
        REFERENCES student_group_sessions(id)
        ON DELETE SET NULL,

    occurrence_date DATE NOT NULL,

    actual_start_time TEXT NOT NULL DEFAULT '',
    actual_end_time TEXT NOT NULL DEFAULT '',

    status TEXT NOT NULL DEFAULT 'scheduled',

    is_ad_hoc INTEGER NOT NULL DEFAULT 0,

    notes TEXT NOT NULL DEFAULT '',

    created_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    updated_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT student_group_session_occurrences_status_check
        CHECK (status IN ('scheduled', 'completed', 'cancelled')),

    CONSTRAINT student_group_session_occurrences_ad_hoc_check
        CHECK (is_ad_hoc IN (0, 1))
);

CREATE INDEX idx_student_group_session_occurrences_group_date
    ON student_group_session_occurrences(group_id, occurrence_date DESC, id DESC);

CREATE INDEX idx_student_group_session_occurrences_timetable_date
    ON student_group_session_occurrences(timetable_session_id, occurrence_date DESC, id DESC);

CREATE UNIQUE INDEX idx_student_group_session_occurrences_normal_unique
    ON student_group_session_occurrences(group_id, timetable_session_id, occurrence_date)
    WHERE timetable_session_id IS NOT NULL
      AND is_ad_hoc = 0;

CREATE TABLE student_group_session_staff (
    occurrence_id BIGINT NOT NULL
        REFERENCES student_group_session_occurrences(id)
        ON DELETE CASCADE,

    user_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    assignment_role TEXT NOT NULL,

    work_status TEXT NOT NULL,

    notes TEXT NOT NULL DEFAULT '',

    recorded_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    recorded_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    PRIMARY KEY (occurrence_id, user_id),

    CONSTRAINT student_group_session_staff_role_check
        CHECK (TRIM(assignment_role) <> ''),

    CONSTRAINT student_group_session_staff_status_check
        CHECK (work_status IN ('worked', 'absent', 'excused'))
);

CREATE INDEX idx_student_group_session_staff_user
    ON student_group_session_staff(user_id, recorded_at DESC);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM payroll_payments pp
        LEFT JOIN finance_transactions ft
            ON ft.id = pp.finance_transaction_id
        WHERE pp.finance_transaction_id IS NOT NULL
          AND ft.id IS NULL
    ) THEN
        RAISE EXCEPTION
            'cannot add payroll_payments.finance_transaction_id foreign key: orphan finance_transaction_id values exist';
    END IF;
END $$;

ALTER TABLE payroll_payments
    ADD CONSTRAINT payroll_payments_finance_transaction_id_fkey
    FOREIGN KEY (finance_transaction_id)
    REFERENCES finance_transactions(id)
    ON DELETE SET NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM finance_transactions ft
        WHERE ft.source_type = 'payroll_payment'
          AND COALESCE(ft.source_id, 0) > 0
        GROUP BY ft.source_type, ft.source_id
        HAVING COUNT(*) > 1
    ) THEN
        RAISE EXCEPTION
            'cannot add payroll payment finance uniqueness: duplicate finance_transactions source_type/source_id pairs exist';
    END IF;
END $$;

CREATE UNIQUE INDEX idx_finance_transactions_source_payroll_payment
    ON finance_transactions(source_type, source_id)
    WHERE source_type = 'payroll_payment';

ALTER TABLE staff_salary_profiles
    DROP CONSTRAINT IF EXISTS staff_salary_profiles_type_check;

ALTER TABLE staff_salary_profiles
    ADD CONSTRAINT staff_salary_profiles_type_check
    CHECK (
        compensation_type IN (
            'hourly',
            'daily',
            'weekly',
            'monthly',
            'per_student',
            'per_session'
        )
    );

ALTER TABLE payroll_payments
    DROP CONSTRAINT IF EXISTS payroll_payments_type_check;

ALTER TABLE payroll_payments
    ADD CONSTRAINT payroll_payments_type_check
    CHECK (
        compensation_type IN (
            'hourly',
            'daily',
            'weekly',
            'monthly',
            'per_student',
            'per_session'
        )
    );
