CREATE TABLE payroll_payment_calculation_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payroll_payment_id BIGINT NOT NULL
        REFERENCES payroll_payments(id)
        ON DELETE CASCADE,

    detail_type TEXT NOT NULL,

    source_type TEXT NOT NULL DEFAULT '',
    source_id BIGINT,

    label TEXT NOT NULL,
    detail_note TEXT NOT NULL DEFAULT '',

    quantity NUMERIC(14,4) NOT NULL DEFAULT 0,
    rate_snapshot NUMERIC(14,2) NOT NULL DEFAULT 0,
    amount_snapshot NUMERIC(14,2) NOT NULL DEFAULT 0,

    sort_order INTEGER NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT payroll_payment_calculation_details_type_check
        CHECK (
            detail_type IN (
                'per_student_included',
                'per_student_excluded_full_month_leave',
                'per_session_occurrence',
                'summary',
                'manual_note'
            )
        ),

    CONSTRAINT payroll_payment_calculation_details_label_check
        CHECK (TRIM(label) <> ''),

    CONSTRAINT payroll_payment_calculation_details_source_type_check
        CHECK (
            source_type IN (
                '',
                'admission',
                'student_enrollment',
                'student_group_session_occurrence'
            )
        )
);

CREATE INDEX idx_payroll_payment_calculation_details_payment
    ON payroll_payment_calculation_details(payroll_payment_id, sort_order, id);

CREATE INDEX idx_payroll_payment_calculation_details_type
    ON payroll_payment_calculation_details(detail_type, payroll_payment_id);
