CREATE TABLE payroll_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    period_start DATE NOT NULL,
    period_end DATE NOT NULL,

    label TEXT NOT NULL DEFAULT '',

    status TEXT NOT NULL DEFAULT 'draft',

    created_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    approved_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    approved_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT payroll_runs_period_check
        CHECK (period_end >= period_start),

    CONSTRAINT payroll_runs_status_check
        CHECK (
            status IN (
                'draft',
                'calculated',
                'approved',
                'closed'
            )
        )
);

CREATE UNIQUE INDEX idx_payroll_runs_period
    ON payroll_runs(period_start, period_end);


CREATE TABLE payroll_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payroll_run_id BIGINT NOT NULL
        REFERENCES payroll_runs(id)
        ON DELETE RESTRICT,

    user_id BIGINT NOT NULL
        REFERENCES users(id)
        ON DELETE RESTRICT,

    salary_profile_id BIGINT
        REFERENCES staff_salary_profiles(id)
        ON DELETE SET NULL,

    division_id BIGINT
        REFERENCES divisions(id)
        ON DELETE SET NULL,

    training_program_id BIGINT
        REFERENCES training_programs(id)
        ON DELETE SET NULL,

    compensation_type TEXT NOT NULL,

    rate_snapshot NUMERIC(14,2) NOT NULL DEFAULT 0,

    quantity NUMERIC(14,4) NOT NULL DEFAULT 1,

    quantity_label TEXT NOT NULL DEFAULT '',

    base_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    additions_total NUMERIC(14,2) NOT NULL DEFAULT 0,

    deductions_total NUMERIC(14,2) NOT NULL DEFAULT 0,

    net_amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    status TEXT NOT NULL DEFAULT 'draft',

    payment_method TEXT NOT NULL DEFAULT '',

    payment_reference TEXT NOT NULL DEFAULT '',

    paid_at TIMESTAMPTZ,

    paid_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    finance_transaction_id BIGINT,

    notes TEXT NOT NULL DEFAULT '',

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT payroll_payments_type_check
        CHECK (
            compensation_type IN (
                'hourly',
                'weekly',
                'monthly',
                'per_student'
            )
        ),

    CONSTRAINT payroll_payments_status_check
        CHECK (
            status IN (
                'draft',
                'calculated',
                'approved',
                'paid',
                'void'
            )
        ),

    CONSTRAINT payroll_payments_amount_check
        CHECK (
            rate_snapshot >= 0
            AND quantity >= 0
            AND base_amount >= 0
            AND additions_total >= 0
            AND deductions_total >= 0
            AND net_amount >= 0
        )
);

CREATE INDEX idx_payroll_payments_run
    ON payroll_payments(payroll_run_id);

CREATE INDEX idx_payroll_payments_user
    ON payroll_payments(user_id);

CREATE INDEX idx_payroll_payments_status
    ON payroll_payments(status);

CREATE UNIQUE INDEX idx_payroll_payments_run_profile
    ON payroll_payments(
        payroll_run_id,
        user_id,
        salary_profile_id
    )
    WHERE salary_profile_id IS NOT NULL;


CREATE TABLE payroll_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payroll_payment_id BIGINT NOT NULL
        REFERENCES payroll_payments(id)
        ON DELETE CASCADE,

    adjustment_type TEXT NOT NULL,

    direction TEXT NOT NULL,

    description TEXT NOT NULL DEFAULT '',

    amount NUMERIC(14,2) NOT NULL DEFAULT 0,

    created_by_user_id BIGINT
        REFERENCES users(id)
        ON DELETE SET NULL,

    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT payroll_adjustments_type_check
        CHECK (
            adjustment_type IN (
                'incentive',
                'bonus',
                'allowance',
                'overtime',
                'deduction',
                'salary_advance',
                'correction',
                'other'
            )
        ),

    CONSTRAINT payroll_adjustments_direction_check
        CHECK (
            direction IN (
                'addition',
                'deduction'
            )
        ),

    CONSTRAINT payroll_adjustments_amount_check
        CHECK (amount > 0)
);

CREATE INDEX idx_payroll_adjustments_payment
    ON payroll_adjustments(payroll_payment_id);
