ALTER TABLE one_to_one_bookings
    ADD COLUMN IF NOT EXISTS coach_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE one_to_one_bookings
    ADD COLUMN IF NOT EXISTS package_status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE one_to_one_bookings
    ADD COLUMN IF NOT EXISTS completed_sessions INTEGER NOT NULL DEFAULT 0;

ALTER TABLE one_to_one_bookings
    ADD COLUMN IF NOT EXISTS cancelled_sessions INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_one_to_one_bookings_coach
    ON one_to_one_bookings(coach_user_id);

CREATE INDEX IF NOT EXISTS idx_one_to_one_bookings_status
    ON one_to_one_bookings(package_status);

CREATE TABLE IF NOT EXISTS one_to_one_booking_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL REFERENCES one_to_one_bookings(id) ON DELETE CASCADE,
    schedule_id BIGINT NOT NULL UNIQUE REFERENCES space_schedules(id) ON DELETE CASCADE,
    session_number INTEGER NOT NULL,
    coach_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    coach_fee NUMERIC NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'scheduled',
    attendance_status TEXT NOT NULL DEFAULT '',
    attendance_note TEXT NOT NULL DEFAULT '',
    attendance_marked_at TIMESTAMPTZ,
    attendance_marked_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    completed_at TIMESTAMPTZ,
    completed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    cancelled_at TIMESTAMPTZ,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    UNIQUE (booking_id, session_number)
);

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS coach_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS coach_fee NUMERIC NOT NULL DEFAULT 0;

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'scheduled';

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS attendance_status TEXT NOT NULL DEFAULT '';

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS attendance_note TEXT NOT NULL DEFAULT '';

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS attendance_marked_at TIMESTAMPTZ;

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS attendance_marked_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS completed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ;

ALTER TABLE one_to_one_booking_sessions
    ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_one_to_one_booking_sessions_booking
    ON one_to_one_booking_sessions(booking_id, session_number);

CREATE INDEX IF NOT EXISTS idx_one_to_one_booking_sessions_schedule
    ON one_to_one_booking_sessions(schedule_id);
